name: Push API Image

on:
  workflow_run:
    workflows: ["Push Training Image"]
    types:
      - completed

jobs:
  push-api:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push API Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t buy-wait-api \
            -f "FAST API/Dockerfile" "FAST API" \
            --load
          
          docker tag buy-wait-api:latest ${{ steps.login-ecr.outputs.registry }}/buy-wait-api:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/buy-wait-api:latest
